on:
  repository_dispatch:
    types: [homebrew-pr]

jobs:
  run_on_hook:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_WRITE }}

      - name: Generate Homebrew Formula
        run: |
          ls -l "$PWD"
          APP_VERSION=${{ github.event.client_payload.version }}
          APP_SHA256=${{ github.event.client_payload.sha }}
          echo "VERSION: $APP_VERSION"
          echo "SHA256: $APP_SHA256"

          cat "$PWD"/templates/scala-deps.rb.template | sed "s/\$VERSION/$APP_VERSION/g" | sed "s/\$SHA256/$APP_SHA256/g" > scala-deps.rb
          cat scala-deps.rb
          BRANCH="version_$APP_VERSION"
          git checkout -b "$BRANCH"
          git add .
          git commit -m"Update to scala-deps version to $APP_VERSION"
          git push origin "$BRANCH"
          gh pr create --title "Update to $APP_VERSION" --body "Bump scala-deps version to $APP_VERSION"

        env:
          GH_TOKEN: ${{ secrets.REPO_WRITE }}
