on:
  repository_dispatch:
    types: [homebrew-pr]

jobs:
  run_on_hook:
    runs-on: macos-latest
    steps:
      - env:
          APP_VERSION: ${{ github.event.client_payload.version }}
          APP_SHA: ${{ github.event.client_payload.sha }}
        run: |
          echo "VERSION: $APP_VERSION"
          echo "SHA256: $APP_SHA"
